---
maintainers:
    - name: "Paul Tagliamonte"
      email: "paultag@example.com"

jobs:
    - name: "scrapers-state-il"
      description: "IL Scrape"
      maintainer: "paultag@example.com"
      crontab: "0 4 * * *"
      timezone: "America/New_York"
      command: "update il --scrape"
      image: "sunlightlabs/scrapers-us-state"
      env: "ocd"
      link: "ocd"
      tags:
          - "ocd"

env-sets:
    - name: "ocd"
      values:
          SUNLIGHT_API_KEY: "ADDMEHERE"
          DATABASE_URL: "postgis://opencivicdata:test@10.42.2.101/opencivicdata"

link-sets:
    - name: "ocd"
      links:
          - remote: "postgres"
            alias: "postgres"
